name: NPM Package Publish

on:
 push:
   branches: [deploy]

jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
        name: Checkout source code
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with :
           version: 16.13.0
       
      - name: publishing NPM package
      - run: npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
